# -*- coding: utf-8 -*-
"""Heart Disease Risk Assessment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPyfV_untlEKV1TCqRi7MrmaISWIrJH6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('heart.csv')
df.head()

print("Null values in dataset:", df.isnull().sum().sum())
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
df = pd.read_csv('heart.csv')
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
input_data = np.array([[63,1,3,145,233,1,0,150,0,2.3,0,0,1]])
prediction = model.predict(input_data)
print("Prediction:", "High Risk" if prediction[0] == 1 else "Low Risk")

!streamlit run app.py